#!/bin/bash

echo "Enter path to wallpaper: "
read -r wallpaper

# Generate colors
wal -c
wal -i $wallpaper -a "75"

swww img $wallpaper

# Copy config over to waybar
cp $HOME/.cache/wal/colors-waybar.css $HOME/.config/waybar/colors.css
cp $HOME/.cache/wal/colors-waybar-rgba.css $HOME/.config/waybar/colors-rgba.css

# Copy config over to wofi
cp $HOME/.cache/wal/colors-waybar.css $HOME/.config/wofi/colors.css
cp $HOME/.cache/wal/colors-waybar-rgba.css $HOME/.config/wofi/colors-rgba.css

# Run script to configure mako
$HOME/.config/scripts/mako-wal

# Restart waybar after script is ran
if pgrep -x "waybar" > /dev/null; then
	killall waybar
	sleep 0.1
	waybar &!
else
	waybar &!
fi
