#!/bin/bash
set -e

printf "Title: "
read TITLE

TITLE="$(echo $TITLE | sed 's/ /_/g')"
DIRNAME="$TITLE-$(date '+%s')"
mkdir -p "$HOME/Videos/$DIRNAME"
SESSION_TYPE=$(echo $XDG_SESSION_TYPE)

if [ $SESSION_TYPE = "wayland" ]; then
	ffmpeg -loglevel fatal -video_size 1920x1080 -f kmsgrab -framerate 60 -i :0.0 -c:v libx264 -preset veryfast "$HOME/videos/screencasts/$DIRNAME/video.mkv" & printf "Video recording started.\n"
elif [ $SESSION_TYPE = "X11" ]; then
	ffmpeg -loglevel fatal -video_size 1920x1080 -f x11grab -framerate 60 -i :0.0 -c:v libx264 -preset veryfast "$HOME/videos/screencasts/$DIRNAME/video.mkv" & printf "Video recording started.\n"
elif [ $SESSION_TYPE = "tty" ]; then
	printf "Please start a display server\n"
	kill $(pgrep screencast)
else
	printf "Unknown display server. Please check if you have Xresources or XDG setup correctly.\n"
	kill $(pgrep screencast)
fi

printf "Press enter to stop recording\n"
read lol
kill $(pgrep ffmpeg)

printf "Recording stopped\n"
