--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chinh4thepro/Pictures/wallpapers/retrowave.png"

-- Special
background="#0A0C1B"
foreground="#adc7e0"
cursor="#adc7e0"

-- Colors
color0="#0A0C1B"
color1="#8B6372"
color2="#3D5786"
color3="#5B6394"
color4="#9B699E"
color5="#D6709E"
color6="#618AAB"
color7="#adc7e0"
color8="#798b9c"
color9="#8B6372"
color10="#3D5786"
color11="#5B6394"
color12="#9B699E"
color13="#D6709E"
color14="#618AAB"
color15="#adc7e0"
