# Shell variables
# Generated by 'wal'
wallpaper='/home/chinh4thepro/Pictures/wallpapers/retrowave.png'

# Special
background='#0A0C1B'
foreground='#adc7e0'
cursor='#adc7e0'

# Colors
color0='#0A0C1B'
color1='#8B6372'
color2='#3D5786'
color3='#5B6394'
color4='#9B699E'
color5='#D6709E'
color6='#618AAB'
color7='#adc7e0'
color8='#798b9c'
color9='#8B6372'
color10='#3D5786'
color11='#5B6394'
color12='#9B699E'
color13='#D6709E'
color14='#618AAB'
color15='#adc7e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
