#!/usr/bin/env bash

entries="Lock\nLogout\nSuspend\nReboot\nShutdown"

selected=$(echo -e $entries|wofi --width 250 --height 160 --dmenu | awk '{print tolower($1)}')

case $selected in
  lock)
    exec $HOME/.config/scripts/lock;;
  logout)
    hyprctl dispatch exit;;
  suspend)
    exec $HOME/.config/scripts/lock & sleep 1 && systemctl suspend;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff;;
esac
